<?php

namespace App\Filament\Pages;

use Filament\Pages\Page;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Str;

class VueTestPage extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.vue-test-page';

    public function getTitle(): string | Htmlable
    {
        return '';
    }

    public function render(): View
    {
        // $this->page['props']['php_version'] = phpversion();
        // $this->page['url'] = Str::start(Str::after(request()->fullUrl(), request()->getSchemeAndHttpHost()), '/');
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
